spring:
  thymeleaf:
    cache: false
    prefix: /WEB-INF/views/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost/jejunu?characterEncoding=utf-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    data: classpath:/resources/import.sql
  resources:
    static-locations: /WEB-INF/views/spring/resources
  jpa:
    hibernate:
      ddl-auto: validate
